### PR TITLE
Fix gl-renderer link error

### PR DESCRIPTION
**Pull request by ginkage**
Adds necessary dependencies required after ff6b9c59b474d8c7d5bdac8aea90038d23b2ad84

### CODE REVIEW

**Comment by JeffyCN** [comment]
thanks for the patch, i've squashed it into that commit.

i was building it with buildroot rootfs, and the mali GPU's egl pkgconfig including libdrm dependency, that's why i didn't hit this error :)

**Comment by ginkage** [comment]
Out of curiosity: drm-backend doesn't work with the current mali blob (g13p0-10) due to missing `gbm_bo_get_fd_for_plane` symbol, so I'm guessing some new blob (based on r46) is coming soon?

**Comment by JeffyCN** [comment]
check: https://github.com/JeffyCN/mirrors/tree/libmali

there's a hook to provide those api

**Comment by ginkage** [comment]
Hm, thanks, that helped... I still can't get gles working with xwayland though.

**Comment by JeffyCN** [comment]
that might need libmali with x11 and wayland backends, but only rk3588's mali has it.

otherwise maybe try upstream's opensource mali kernel driver and matched mesa

**Comment by ginkage** [comment]
Yeah, I'm running it with `libmali-valhall-g610-g13p0-x11-wayland-gbm.so`, somehow it doesn't work. Maybe I'm doing something wrong...

**Comment by JeffyCN** [comment]
it looks like the xwayland's glamor depends on mesa's wl_drm protocol, which is not supported by the libmali.

so you might need to try upstream version or non-xserver xwayland(i think someone tested it with kwin's xwayland)

**Pull request closed without merging**
